### ISSUE TITLE
T1 Officer (Panzer Tactics) has two sprints after "For the Fatherland" global upgrade

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#101]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** SS global for the fatherland ability upgrade will give two charge abilities to their T1 officer (Panzer-tactics)
**Steps to Reproduce:** 
1) Call in T1 officer Panzer-tactics
2) Buy global for the fatherland upgrade

**Expected Outcome:** Officer keeps his officer-charge, remains unaffected by the upgrade
**Actual Outcome:** Gets a free extra sprint charge, officer now gets two different charges with two seperate timers

---
**Additional Information:** No extra info
**Attachments:** 

**Reporter:** Blarg_Master#1931

![image](https://user-images.githubusercontent.com/76040686/102713684-54e43100-42ca-11eb-8ec0-08ede213706f.png)

**Comment by Stoklomolvi** [comment]
Officers were reworked; this bug is no longer valid.
