### ISSUE TITLE
UK Armor Major doesn't want to be summoned

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#102]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** UK Armor Major doesn't want to be summoned 
**Steps to Reproduce:** 
1. Go UK Armor (my case is Armor Anvil)
2. Summon the Valentine Captain

**Expected Outcome:** Able to summon Major if already open the Tank Building or reach CP4
**Actual Outcome:** Major summoning is locked, with the description "Only 1 Major can be at field"

---
**Additional Information:**
1. Doesn't apply vice versa (Major summon won't lock the Captain summon)
2. Summoning the non tank Captain won't cause this bug
3. A good way to circumvent the bug is to kill the Captain or wait until you can summon Major first or summon the non tank Captain from Light Vic building
4. Duplicate of #97 with some useful info

**Attachments:**

**Reporter:** Alisha Hellewaage#0610

![image](https://user-images.githubusercontent.com/76040686/102713869-582bec80-42cb-11eb-9979-2ec28aa31371.png)

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.0.
