### ISSUE TITLE
SS Propaganda "Unit Training" not working

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#104]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** SS Propaganda "Unit Training" not working
**Steps to Reproduce:** 
1) Go SS Propaganda
2) Wait for 3 CP to unlock "Unit Training" doctrinal ability
3) Try to use it on a friendly unit

**Expected Outcome:** The selected unit is granted veterancy based on it's type (Usually 2 stars, and only for units 2 stars or less)
**Actual Outcome:** No unit can be selected

---
**Additional Information:** Due to a fix of the ability (Previously the ability could target allied units too, leading to a strong and unfair buff in veterancy for any and all units)
**Attachments:** None

**Reporter:** Luke7O7#8538

**Comment by Stoklomolvi** [comment]
Fixed by v1.0.6.
