### ISSUE TITLE
UK Armor Command Tanks calling arty on themselves

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#110]
**Game Version:** Sperhead version 1.0.5
**Summary of Bug:** UK Armour doctrine command tanks will call in artillery on themselves, not the target location
**Steps to Reproduce:** 
1) Using either UK Armour command tank
2) Use the standard off map barrage ability

**Expected Outcome:** Artillery is called in where clicked
**Actual Outcome:** Barrage is centrered on the tank itself, not where called in. 

---
**Additional Information:** None

**Reporter:** Blarg_Master#1931

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
