### ISSUE TITLE
UKF Airborne Loiter last longer than it should

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#116]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** UKF Airborne Loiter last longer than it should
**Steps to Reproduce:** 
1. Go UKF Airborne (Anvil or Hammer doesn't really matter)
2. Get the Captain and/or Major
3. Try to use their loiters

**Expected Outcome:** Once the timer runs out, the plane depart the map
**Actual Outcome:** Loiter still fully operational way longer (Plane still shooting even though cooldown of call in skill is done)

---
**Additional Information:**
1. This is the same issue way back during when Achronos is still the head dev of the mod
2. All Loiters (Both Captain and Major,Anvil or Hammer, and on any type of Loiter {Combat Patrol, Overwatch or Standard}) have this issue
3. The Planes DOESN'T shoot way beyond the circle like back in the day

**Reporter:** Alisha Hellewaage#0610

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
