### ISSUE TITLE
The hotkey for .30 cal HMG (both variants) armour piercing rounds is the same as the one to leave a building

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#117]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** The hotkey for .30 cal HMG (both variants) armour piercing rounds is the same as the one to leave a building (hotkey: D)
**Steps to Reproduce:** 
1. Play as USA
2. Put .30 cal machinegun in building
3. Hotkey for AP rounds makes unit leave building

**Expected Outcome:** Switch to armour piecing
**Actual Outcome:** Unit leaves building

---
**Additional information:** None

**Reporter:** Muro#4224

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.1.1.
