### ISSUE TITLE
Feldfunkgerät retreat point

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#119]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** Feldfunkgerät not being a retreat point
**Steps to Reproduce:**
1) Go OKW
2) Upgrade with Forward HQ
3) Build Feldfunkgerät

**Expected Outcome:** The antenna acts as a retreat point like said in description
**Actual Outcome:**  Can call out battlegroups and support, but can't be set as retreat point

---
**Additional Information:** None
**Attachments:**
![image](https://user-images.githubusercontent.com/76040686/103740317-4babd180-4ff7-11eb-8b03-a7ac8efa66e0.png)

**Comment by Stoklomolvi** [comment]
No longer valid bug report at this time due to removal of Feldfunkgerät.
