### ISSUE TITLE
WP shells fire quicker than targeted HE shells, other loaded shell types. 

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#121]
**Game Version:** 1.0.6 stok
**Summary of Bug:** WP shot on most tanks bugged, fires too fast, maybe too accurate
**Steps to reproduce:**

1.) go US armor, get a 75 command tank, or valentine with WP, or churchil with WP,
2.) use WP, compare wind up time vs 75mm HE on, say, sherman V from UK, or wind up time, its accuracy vs HE, etc

**Expected outcome:** it should be similar in wind up too HE and accuracy too the HE shell, right? 
**Actual outcome:** it feels really quick with its aim time when casting the ability too when the shell fires and hits, vs say a targeted HE shell, and i think it misses very little compared too the HE shell,

**Additional information:** its range is also equal too main gun range, vs normal HE shell which is slightly less. but russian frag rounds also have range equal too the main gun range, so maybe its intentional but, even if accuracy may just me getting lucky, it definitely appears too fire faster than a targeted HEAT round or HE round, or stuff like smoke round, canister shot, fragmentation round, etc.

**Comment by Stoklomolvi** [comment]
White phosphorus was removed from British vehicles, so this bug is no longer valid.
