### ISSUE TITLE
Luft fallschirmjager leader MG strafe has additional delay before its called in

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#124]
**Game Version:** 1.0.6 stok version
**Summary of Bug:** the MG strafe (and i think other strafes on his upgrades) has an additional delay before the flares come in, and in which the squad is sorta locked in too calling in the strafe vs other strikes.
**Steps to reproduce:**

1. go wehr luft
2. get the fallschirmjager officer (through infil, or the forward encampment
3. try their base MG strike
4. compare too something like the fragmentation bomb strike, or smoke strafe

**Expected outcome:** the red flares come down immediately upon calling in the strike
**Actual outcome:** theres like a 2-3 second delay before they come in.

**Additional information:** enemy infantry also get a voice call out ("airstrike incoming!") when the strike is called in but before the red flares appears.

edit: it also seems like this is a bug with the ability itself, the MG strafe ability on the 251 halftrack has similar issues.

**Comment by Stoklomolvi** [comment]
No longer applicable due to officer rework.
