### ISSUE TITLE
120mm mortar precision strike without cooldown

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#126]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** 120mm mortar precision strike without cooldown
**Steps to Reproduce:** 
1) Pick commander with access to 120mm towed mortar (Wehr Straffe/Sov Shock)
2) Set up, fire a precision shot

**Expected Outcome:** All mortar barrages receiving a cooldown
**Actual Outcome:** No cooldown, you can fire as fast as your munition allows you to

---
**Additional Information:** None

**Reporter:** SzabóImi#2171

**Comment by Stoklomolvi** [comment]
Cannot duplicate as of 1.0.6.
