### ISSUE TITLE
OKW unit build bug

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#128]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** Basic mortar unit on OKW/versatile infantry general did not recruit
**Steps to Reproduce:** N/A

**Expected Outcome:** Unit to be recruited
**Actual Outcome:** Resources dropped unit showed on recruitment queue for a second than vanished 

---
**Additional Information:** I lost T1 HQ in the game and built all 3 HQs in the same zone. Additionally 1 basic grenadier unit cliped off from the bridge and gut stuck underneath. 
Additional note : This bug also occured on other crewed weapons in T1 building and light vehicles for T2 building
**Attachments:** i have a gameplay file if needed

**Comment by GamingWubba93** [comment]
My friend and I are also experiencing this bug with both Spearhead I & II. It always seems to happen to both the T1/T2 buildings.

**Comment by Stoklomolvi** [comment]
Unable to reproduce in v1.1.1.3.
