### ISSUE TITLE
Long Tom Creeping Barrage fires too fast and is too cheap for how fast he fires

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#133]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** Long Tom Creeping Barrage fires too fast and is too cheap for how fast he fires
**Steps to Reproduce:** 
1) Pick USF rangers 
2) Fire a long tom creeping barrage

**Expected Outcome:** A slow, relatively weak attack that will obliterate static defenses with his accuracy
**Actual Outcome:** A rapid-fire rain of death and hellish destruction on an entire sector

---
**Additional Information:** it should cost a lot more or have a much lower ROF IMO
**Attachments:** N/A

**Reporter:** RalphRoberts#6160

**Comment by RalphRoberts** [comment]
This isn't a bug, it's a balance complaint. It's also been 'fixed' because Long Tom is no longer in Ranger.
