### ISSUE TITLE
Unit ability window going over to other units

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#139]
**Game Version:** Version 1.0.6
**Summary of Bug:** Unit ability window going over to other units
**Steps to Reproduce:** 
1) Only time it happened was as USF
2) Go USF Rifle
3) Make a Sherman M4A2
4) Call in a T1 Officer
5) Try to click on one then on the other

**Expected Outcome:** As you click on the unit it's ability bar shows with it's abilities
**Actual Outcome:** Once the officer is clicked, it has all the Sherman abilities (Reverse, toggle Shell, accelerate, etc.)
All abilities other than Attack Order and Halt are replaced, hotkey for retreat wouldn't work.

---
**Additional Information:** Only started happening recently, never had the problem before
**Attachments:** None

**Reporter:** Luke7O7#8538

**Comment by Stoklomolvi** [comment]
Cannot reproduce.
