### ISSUE TITLE
USF and UKF M15 halftrack is vanilla 

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#141]
**Game Version:** Current Stoklomolvi version 1.6
**Summary of Bug:** USF and UKF M15 halftrack is vanilla 
**Steps to Reproduce:** 
1) Select USF doctrine which have acces to them (exp: USF airborn, UKF artillery)
2) Order 1 on the battlefield
3) On the other side, order lot of infantry with small arms and send it againts the m15 not too close

**Expected Outcome:** M15 wins slowly as infantry deal minimal damage unless close damage it. Meanwhile having several abilities.
**Actual Outcome:** Small arms damage and kill it rather fast. No abilities apart from basics (crew can exist USF version) 

---

**Additionnal information:** None

**Reporter:** SzabóImi#2171

**Comment by Stoklomolvi** [comment]
Duplicate of #61
