### ISSUE TITLE
Every icon and unit model is incorrect.

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#142]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** Every icon and unit model is incorrect.
**Steps to Reproduce:** No idea
**Expected Outcome:** Icons and unit models should be working as intentional.
**Actual Outcome:** Icons and Units are bugged.

---

**Additional Information:** Says its a engineer squad but its a T-34 and looks like a Mg squad.
**Attachments:** No attachment at this time.

**Reporter:** R𝖊𝖋𝖚𝖘𝖊𝖉𝕷𝖀𝖁#5230

**Comment by Stoklomolvi** [comment]
Happens only if the player has been swapping tuning mods without restarting the game. Nothing I can do from the mod perspective.
