### ISSUE TITLE
US Rifle Sniper kills vehicle

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#143]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** Sniper kills vehicle
**Steps to Reproduce:** 
1) Use US Rifle
2) Spawn the doctrinal sniper and shoot the enemy vehicle

**Expected Outcome:** It shouldn't do anything
**Actual Outcome:** It kills the vehicle in one or two hits

---

**Additional Information:** Snipers aim at vehicles on their own
**Attachments:** <images, attachments, etc.>

**Reporter:** Mr.B#8039

**Comment by Stoklomolvi** [comment]
Intended behaviour in v1.0.6; also v1.0.7 is final version for Spearhead I.
