### ISSUE TITLE
Leichte Panther Commander and Panther A share hotkey "A" 

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#147]
**Game Version:** Stok 1.0.6
**Summary of Bug:** Leichte Panther Commander and Panther A share hotkey "A" 
**Steps to Reproduce:** 
1) Go Wehr Leichte
2) Build T4

**Expected Outcome:** Different hotkey
**Actual Outcome:** Same Hotkey *

**Reporter:** Constantino#9135

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.5.
