### ISSUE TITLE
Panzer IV H and Panzer IV G share hotkey "V" 

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#148]
**Game Version:** Spearhead version 1.0.6
**Summary of Bug:** Panzer IV H and Panzer IV G share hotkey "V" 
**Steps to Reproduce:**
1) Go Wehr Leichte
2) Build T3

**Expected Outcome:** Different hotkey
**Actual Outcome:** Same Hotkey

**Comment by Stoklomolvi** [comment]
Panzer IV Ausf. G hotkey changed from V to G.
