### ISSUE TITLE
Vanilla range on main gun of churchill croc

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#154]
**Game Version:** Spearhead version 1.0.7
**Summary of Bug:** Vanilla range on main gun of churchill croc
**Steps to Reproduce:** 
1) Use go royal tank 
2) Deploy churchill crocodile

**Expected Outcome:** Have range of other churchills
**Actual Outcome:** Less than half the range, activated abilities (WP and HE still work at their normal ranges)

**Reporter:** storm60#1006

**Comment by RalphRoberts** [comment]
Closing as CLOSED
