### ISSUE TITLE
US E8 Mech commander Time on target barrage has no Info Text

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#156]
**Game Version:** Spearhead version 1.0.7
**Summary of Bug:** US E8 Mech commander Time on target barrage has no Info Text
**Steps to reproduce:**
1) Go US 
2) pick Mech 
3) Call in the E8 commander and Hover over the Time on Target barrage

**Expected Outcome:** Information on the Delay, Number of rounds, muni cost etc.
**Actual outcome:** No Information on the Time on Target barrage for US E8 Mech Commander

**Reporter:** Tachikaze#1526

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
