### ISSUE TITLE
OKW Stug III G missing individual smoke dispenser upgrade

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#157]
**Game Version:** Spearhead version 1.0.7
**Summary of Bug:** OKW Stug III G missing individual smoke dispenser upgrade
**Steps to Reproduce:** 
1) Go OKW
2) Build Stug 3 G
3) Check unit HUD

**Expected Outcome:** Should have upgrade like all other Stugs
**Actual Outcome:** Doesn't 

**Reporter:** Constantino#9135

**Comment by Stoklomolvi** [comment]
StuG III Ausf. G tanks have been reworked into ambush tanks.
