### ISSUE TITLE
Tulip (Fireflies) having theoric infinite range

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#164]
**Game Version:** Spearhead version 1.0.7
**Summary of Bug:** Tulip (Fireflies) having theoric infinite range
**Steps to Reproduce:**
1) Go UKF Armored Hammer
2) Get Sherman Firefly, upgrade with Tulip rocket
3) Target a tank out of displayed range

**Expected Outcome:** Firefly moves to get in range before firing rockets
**Actual Outcome:** Fire rockets towards the target

---
**Additional Information:**  It seems that some height difference can easily make the rocket miss at pretty long ranges, but it is proven working on flat maps. Will provide evidence when I can.
**Attachments:**
![image](https://user-images.githubusercontent.com/76040686/113523106-2868d200-95a6-11eb-8d4e-6d068fbd0523.png)

**Comment by Stoklomolvi** [comment]
Fixed as of 1.0.1 by disabling ignore range requirements
