### ISSUE TITLE
Wehrmacht, Leichte Division, 90. Grenadier Leutnant (outside the Sdkfz at foot) with rapid mortar barrage fires at himself

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#165]
**Game Version:**  Spearhead Version 1.0.7
**Summary of Bug:** Wehrmacht, Leichte Division, 90. Grenadier Leutnant (outside the Sdkfz at foot) with rapid mortar barrage fires at himself, if an enemy is directly aimed with the red crosshair (don't happens if target is the open field)
**Steps to Reproduce:** 
1) Use Wehrmacht
2) Chooose Leichte Division
3) Build Leutnant
4) Get his Sdkfz destroyed
5) Upgrade to rapid barrage, aim the rapid barrage directly on enemy

**Expected Outcome:** Mortars should hurt the enemy
**Actual Outcome:** Friendly fire with spreaded barrage

**Reporter:** Cool McCool#2992

**Comment by Stoklomolvi** [comment]
No longer applicable due to officer rework.
