### ISSUE TITLE
US Mech Doc M4A3(75)W HVSS Sherman missing sandbag upgrade.

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#173]
**Game Version:** Spearhead Version 1.0.7
**Summary:** US Mech Doc M4A3(75)W HVSS Sherman missing sandbag upgrade.
**Steps to reproduce:** 
1) Go USF Mech
2) Deploy M4A3(75)W HVSS

**Expected outcome:** Upgrade should be present to be consistent with all other M4A3 variants (only other exception is Armored Doc E8; already reported).
**Actual outcome:** Upgrade missing. 

**Reporter:** Constantino#9135

**Comment by RalphRoberts** [comment]
Inconsistent availability of upgrades is not a bug unless explicitly stated that the unit is supposed to have them. I would be shocked if this unit was meant to have sandbags, since it already has superior armor and moving accuracy compared to a normal sherman.
