### ISSUE TITLE
US Ranger incorrect stats card

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#174]
**Game Version:** Spearhead Version 1.0.7 
**Summary:** US Ranger's M4A3E2 has Either the incorrect stat Card or Info on its Main Gun as it has the pen and Reload of the 75M3 but it states it has the 76M1 
**Steps to Reproduce:** 
1) Pick US Ranger
2) Build M4A3E2
3) Compare Stat card with that of a M4 75 and of a M4 76 

**Expected Outcome:** It has the Same Pen and Reload of the 76M1 on Tanks like the M4A2 76, M4A376 HVSS 
**Actual Outcome:** Has the Reload, Pen and Accuracy Rate of the 75M3 found on M4 75 tanks instead of the 76M1 it is stated to have. 

**Reporter:** Tachikaze#1526

**Comment by RalphRoberts** [comment]
This bug report was either made in error or fixed sometime in the last two years, because the jumbo has been repeatedly confirmed since then to have a 76mm gun.
