### ISSUE TITLE
SS Propaganda Tiger Ace Missing abilities

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#177]
**Game Version:** Spearhead 2 Version 1.0.0 
**Summary of Bug:** SS Propaganda Tiger Ace Missing abilities
**Steps to Reproduce:** 
1) Go SS-Propaganda
2) Call in a Tiger Ace

**Expected Outcome:** A bunch of abilities like the incendiary shells
**Actual Outcome:** Very few abilities and patch notes mention no Tiger Ace nerf

---
**Attachment:**

**Reporter:** Valentine#9682

![image](https://user-images.githubusercontent.com/76040686/118047212-be98d080-b37a-11eb-8d7e-a48f481079f2.png)

**Comment by Stoklomolvi** [comment]
Fixed by restoring accidentally deleted Tiger Ace.
