### ISSUE TITLE
Mech Sherman 75mm M2A3 missing single shot HE round

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#179]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** Mech Sherman 75mm M2A3 missing single shot HE round.
**Steps to Reproduce:** 
1) Go USF Mech
2) Deploy Sherman M2A3

**Expected Outcome:** Have single shot HE round.
**Actual Outcome:** Doesn't. 

**Reporter:** Constantino#9135

**Comment by Stoklomolvi** [comment]
Fixed early on in v1.0.1 development.
