### ISSUE TITLE
Unit's manpower cost in the British faction arty doctrine is inconsistent

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#180]
**Game Version:** Spearhead II - Stoklomolvi Version v1.0.0
**Summary of Bug:** One unit's manpower cost in the British faction arty doctrine is inconsistent with the changes that have been made between Spearhead I - Stoklomolvi v1.0.7 and Spearhead II - Stoklomolvi Version v1.0.0
**Steps to Reproduce:** 
1) Go UKF Arty
2) Reach 2 command points
3) Use Infiltrate Lieutenant ability

**Expected Outcome**: Lieutenant costs 260 manpower and 20 munitions in accordance with new "regular" skill designation units
**Actual Outcome:** Lieutenant costs 240 manpower and 20 munitions contrary to the cost of other "regular" skill designation units

---
**Additional Information**: The ability costs 240 manpower on every map
**Attachments:**

**Reporter:** b4gle#6240
![image](https://user-images.githubusercontent.com/76040686/118115672-8b415a80-b3e9-11eb-82a1-fd175888ac98.png)

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.0.
