### ISSUE TITLE
Forward deploy and infiltration soviet shock units are cheaper than their regular training 

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#181]
**Game Version:** Spearhead II - Stoklomolvi Version v1.0.0
**Summary of Bug:** Forward deploy and infiltration soviet shock units are cheaper than their regular training 
**Steps to Reproduce:** 
1) Go Soviet shock doctrine
2) Forward deploy and infiltrate units. 

**Expected Outcome**: Cost of the infiltration units is higher/same
**Actual Outcome:** Cost of infiltration units is cheaper, 360 mp compared to 400 from regular training. 

---
**Additional Information**: Happens to both shock engineers and shock unit.

**Reporter:** Muro#4224

**Comment by Stoklomolvi** [comment]
Fixed by unifying costs.
