### ISSUE TITLE
Jagdpanzer IV/70 can buy long-range shot ability at vet 1, but needs vet 2 to use it.

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#182]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** Jagdpanzer IV/70 can buy long-range shot ability at vet 1, but needs vet 2 to use it.
**Steps to Reproduce:**
1) Go SS Panzerjager/Wehr Infanterie
2) Deploy Jagdpanzer IV
3) Upgrade at vet 1 with Long Ranged Shot

**Expected Outcome:**  Long-range shot ability should be usable at vet 1 like for all other units with the ability.
**Actual Outcome:** Can't use long-range shot at vet 1. 

**Reporter:** Constantino#9135

**Comment by RalphRoberts** [comment]
Closed as duplicate
