### ISSUE TITLE
 Soviet Motorized Major is really screwed up; he has placeholder "reee" text, IL-2 overwatch and IL-2 rocket 

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#186]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** Soviet Motorized Major is really screwed up; he has placeholder "reee" text, IL-2 overwatch and IL-2 rocket strafe share hotkey "X", also IL-2 overwatch overlaps with reinforce key, so squad can't reinforce lol.
**Steps to Reproduce:** 

1) Play Soviet Motorized Tactics 
2) Build Major Unit from HQ
3)  Upgrade with IL-2 Abilities

**Expected Outcome:**  Shouldn't be so broken.
**Actual Outcome:** Is really broken. 

**Reporter:** Constantino#9135

**Comment by Stoklomolvi** [comment]
Fixed by officer reworks.
