### ISSUE TITLE
 Elefant "long"-range shot range is shorter than normal range.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#188]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** Elefant "long"-range shot range is shorter than normal range.
**Steps to Reproduce:** 

1) Select Ostheer ost division
2) Build Elefant tank
3) Upgrade with vet 1 long shot ability and compare to current range

**Expected Outcome:**  Ability should give longer range than normal firing.
**Actual Outcome:** Doesn't. 

**Reporter:** Constantino#9135

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.5 with the removal of range increases from veterancy (likely source of this bug).
