### ISSUE TITLE
Leichte Command Panther is buildable unit rather than being a call-in ability like all other tank commanders including the Command Panther from SS Armored.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#199]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** Leichte Command Panther is buildable unit rather than being a call-in ability like all other tank commanders including the Command Panther from SS Armored.
**Steps to Reproduce:** 

1) Go Ostheer Leicthe Company
2) Build Panzerhalle and click tank commander

**Expected Outcome:**  Should be a call-in ability.
**Actual Outcome:** Isn't.        
**Reporter:** Constantino#9135

**Comment by Stoklomolvi** [comment]
Not a bug; working as intended.
