### ISSUE TITLE
Soviet TD's First Officer's 76mm AP Fire for Effect Barrage drops shells instantly.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#202]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** Soviet TD's First Officer's 76mm AP Fire for Effect Barrage drops shells instantly.
**Steps to Reproduce:** 

1) Select soviet TD Doctrine 
2) Tech to Tier 1, get Soviet TD's first officer.
3) Get 76mm AP Fire for Effect Barrage, use it on the enemy.

**Expected Outcome:** Shells have a delay comparable to other Fire for Effect.
**Actual Outcome:** Shells drop instantly.

**Reporter:** Emifas#5368

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
