### ISSUE TITLE
British RAR officer has arty ability slot related bug

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#204]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** British RAR officer has arty ability slot related bug
**Steps to Reproduce:** 

1) Select British Royal Armoured Regiment, anvil
2) Build Troop Post, deploy Royal Tank Regiment Captain
3) Upgrade 4.2-Inch Precision Barrage

**Expected Outcome:** 4.2-Inch Precision Barrage replace with 4.2 Inch HE Barrage in Primary slot
**Actual Outcome**: able to use both Time-on-Target Barrage and HE Barrage. 4.2-Inch Precision Barrage upgrade one just disappeared.
**Additional Information:** if upgrade TOT arty ability, Outcome is same.

**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/125974055-34958a9f-efb1-4253-a43c-f3b5d013bf54.png)

**Reporter:** 생선#5025

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
