### ISSUE TITLE
 AT Teams have no Vet 2

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#209]
**Game Version:**Spearhead II 1.0.0
**Summary of Bug:** AT Teams have no Vet 2
**Steps to Reproduce:** 

1) Make any AT Team
2) Have them vet up to vet 1, then try to achieve vet 2

**Expected Outcome:** Vet 2 gets achieved
**Actual Outcome:** Vet 2 skipped entirely, the squad gets vet 3 instead

**Additional Information:** Stok Knows

**Reporter:** Valhallan 597th#8538

**Comment by Stoklomolvi** [comment]
Fixed as of v1.0.1.
