### ISSUE TITLE
 Soviet ODON T1 Officers barraging/marking from building

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#212]
**Game Version:** Spearhead II version 1.0.0
**Summary of Bug:** Soviet ODON T1 Officers barraging/marking from building
**Steps to Reproduce:**

1) Go Soviet Motorized
2) Deploy T1 officer at 1 CP
3) Put it in building

**Expected Outcome:** No officer ability is available while inside
**Actual Outcome:** Regular barrage and marking infantry is available while selecting building
**Additional Information:** I did not test out additional officers

**Reporter:** Robertoz#0911

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
