### ISSUE TITLE
AT Team Pricing wrong

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#213]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** AT Team Pricing wrong
**Steps to Reproduce:** 

1) Go Soviet Shock
2) Use the Shock troops to construct forward encampment
3) Check the AT Team 

**Expected Outcome:** Costs 240 manpower
**Actual Outcome:** Costs 210 manpower

**Additional Information:**Could be a thing with other encampments

**Reporter:** Valhallan 597th#8538

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.0.
