### ISSUE TITLE
StuG Weapon Upgrades Bugged

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#218]
**Game Version:** Spearhead II Version 1.0.0
**Summary of Bug:** StuG Weapon Upgrades Buggedz
**Steps to Reproduce:**

1) Select OKW Panzerjager
2) Build a StuG

**Expected Outcome:** "Ambush Tactics" and "Smoke Launcher" weapon upgrades available for upgrade (First at vet 1 second right away if munitions are adequate)
**Actual Outcome:** "Ambush Tactics" upped to Veterancy 4 requirement, "Smoke Launchers" removed completely 

**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/126061043-ec396c87-e84e-4687-bad4-08e00a9658d1.png)

**Reporter:** Valhallan 597th#8538

**Comment by Stoklomolvi** [comment]
StuG III Ausf. G tanks have been reworked into ambush tanks.
