### ISSUE TITLE
UKF Grizzly says you need Thunder Run to unlock Willie Pete 

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#222]
**Game Version:** Spearhead II ver. 1.0.0
**Summary of Bug:** UKF Grizzly says you need Thunder Run to unlock Willie Pete 
**Steps to Reproduce:**

1) Play UKF Royal Artillery Regiment.
2) Build a Sherman Grizzly mk1 in Final base.
3) Try to upgrade with Willie Pete 

**Expected Outcome:** Should be able to unlock Willie Pete due, to the fact UKF doesn't have Thunder Run
**Actual Outcome:** Willie Pete is locked behind Thunder Run for UKF

**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/127739954-e59c793e-8e2e-45da-b26f-7ccbb81f93a8.png)

**Reporter:** 𝔓𝔬𝔰𝔰𝔲𝔪 𝔭𝔦𝔢#5230

**Comment by Stoklomolvi** [comment]
As British tanks no longer have access to white phosphorus, this bug is no longer valid.
