### ISSUE TITLE
UKF Commando+Paratrooper Officer Rocket strafe has unlimited range (As long it has vision) and instant cast with plane coming at no delay.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#225]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** UKF Commando+Paratrooper Officer Rocket strafe has unlimited range (As long it has vision) and instant cast with plane coming at no delay.

**Steps to Reproduce:** 
1) Play UKF airborne or commando regiment
2) Get the 2nd officer and obtain rocket strafe, 
3) Have clear vision of the area, and even if outside of range, cast it and see the plane come instantaneously the moment flares drop.

**Expected Outcome:** 5 delay and only able to be cast once within range to do so, and arrives in 5 seconds.
**Actual Outcome:** Ignores range limitation and instant arrival of the plane the moment it is called out.
**Additional Information:** (Might be the same with Airborne but unsure for USF)

**Reporter:** Fortune#9537

**Comment by Stoklomolvi** [comment]
No longer applicable as officers were reworked.
