### ISSUE TITLE
Soviet tier one TD officer can call barrage from inside bunkers

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#226]
**Game Version:** Spearhead II 1.0.0
**Summary of Bug:** soviet tier one TD officer can call barrage from inside bunkers
**Steps to Reproduce:** 

1) Recruit t1 soviet Tank Destroyer doctrine officer, 
2) Put him inside bunker, can call 76mm HE barrage

**Expected Outcome:** not be able to do it
**Actual Outcome:** is able to do it

**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/128514747-befa3a8d-f764-40af-ac69-bf25c9ffcaf6.png)

**Reporter:**Muro#4224

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
