### ISSUE TITLE
The Valentine's Rear Armor and Medium Range Pen Value are higher than it should be.

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#227]
**Game Version:** Spearhead II ver. 1.0.0
**Summary of Bug:** The Valentine's Rear Armor and Medium Range Pen Value are higher than it should be.
**Steps to Reproduce:**

1) Play UKF
2) Create Valentine Tank

**Expected Outcome:** Rear armor should definitely not be 600 (more than the front!), pen at medium range should not be higher than at close range.
**Actual Outcome:** The Valentine has 600 Rear Armor, and 340 Pen at Medium Range.
**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/131839632-0fd9b2a8-2cfa-4626-85ce-779e13591b48.png)
![image](https://user-images.githubusercontent.com/87523678/131839641-57fd7be2-66d7-427b-aad3-f6274e628ba0.png)

**Reporter:** Dankest Inferno#6519

**Comment by Stoklomolvi** [comment]
As intended; on review of the Valentine's armament and armour statistics as they relate to real life, these values closely model what the real values are.
