### ISSUE TITLE
28th USF soldiers (bloody buckets) still have spicy smoke, don't have stun grenade

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#231]
**Game version:** spearhead II 1.0.1
**Summary of bug: **28th USF soldiers (bloody buckets) still have spicy smoke, don't have stun grenade
**Steps to reproduce: **
1) Play USF TD,
2) Train bloody bucket unit
**Expected outcome**: doesn't have spicy smoke
**Actual Outcome**: it does

**Reporter:** Muro#4224

**Comment by Stoklomolvi** [comment]
Fixed in v1.0.2.
