### ISSUE TITLE
M4A2E8  price remains same as last version 

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#232]
**Game version:** spearhead II 1.0.1
**Summary of bug: ** M4A2E8  price remains same as last version 
**Steps to reproduce: **

1) play USF  mech, 
2) Check M4A2E8 price

**Expected outcome**: cost of 420 manpower and 130 fuel
**actual outcome**:  cost of 420 manpower and 90 fuel

**Reporter:** Muro#4224

**Comment by Stoklomolvi** [comment]
Fixed in v1.0.2.
