### ISSUE TITLE
Soviet Rifle Commisar multiple use of the same ability

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#234]
**Game Version:** SH II v. 1.0.1
**Summary of Bug:** Soviet Rifle Commisar multiple use of the same ability
**Steps to Reproduce:** 

1) Go Soviet Rifle
2) Call in the Commisar Officer
3) Upgrade the "Target them!" Ability
4) Use it

**Expected Outcome:** The ability goes on cooldown after being used
**Actual Outcome:** Same as already reported SS Prop officer ability, it goes on cooldown only with the yellow "pool" ticking down, but the ability is still clickable and usable, allowing you to mark multiple units.

**Reporter:** Valhallan 597th#8538

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
