### ISSUE TITLE
 Cant build armoured doc major when you have the captain on the field but you can build the captain when on

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#235]
**Game version:** spearhead II 1.0.1
**Summary of bug:**  Cant build armoured doc major when you have the captain on the field but you can build the captain when only the major is on the field 
**Steps to reproduce:**

1) Play UKF Armoured
2) Call in major unit
 
**Expected outcome:** ability to build both commanders 
**Actual outcome:**  can only have one

**Attachments:**
![image](https://user-images.githubusercontent.com/87523678/132007165-62cc74eb-ebe1-47dd-87e6-4e689eaaa487.png)

**Reporter:**𝔓𝔬𝔰𝔰𝔲𝔪 𝔭𝔦𝔢#5230

**Comment by Stoklomolvi** [comment]
Duplicate of #97 and #102
