### ISSUE TITLE
Unit veterancy status description of faster ability recharge doesn't work

### ISSUE THREAD

**Issue by smassle** [Stoklomolvi/Spearhead-Public#236]
**Game Version:** SH II 1.0.1
**Summary of Bug:**  Unit veterancy status description of faster ability recharge doesn't work
**Steps to Reproduce:** 

1) Build units
2) have them gain veterancy
3) make the veteran and a fresh squad use the same ability, grenade etc.

**Expected Outcome:** the veteran squad should have 20-40% decreased recharge time at vet 3-4
**Actual Outcome:** decrease times are exactly the same ( In my case two non doctrinal USF riflemen one veterancy 0 one veterancy 5)

**Reporter:** Valhallan 597th#8538

**Comment by Stoklomolvi** [comment]
Veterancy was reworked in v1.1.5; bug is no longer valid.
