### ISSUE TITLE
UI for Pioneer and tank disappear

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#262]
Game Version: Spearhead II 1.0.2

Summary of Bug: UI buttons for pioneer and tanks (seems like first batch of these units produced in a new round?) disappear, leaving a blank UI. Only way to fix it seems to to click on another unit and the buttons reset.

Steps to reproduce: Create a pioneer and beginning of round, and then click on him, his buttons for build, etc. will disappear 

Expected Outcome: When you click a unit, their buttons show 

Actual outcome: They sometimes don't

Additional information: I don't recall this ever happening in previous versions.

**Comment by Stoklomolvi** [comment]
While I too have encountered this bug before, it is very difficult to replicate, and I do not believe there is anything I can do here.
