### ISSUE TITLE
tanks can get detracked when crushing unfinished sandbags

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#267]
Game Version: SH II 1.0.2.1
Summary of Bug: Partially built sandbags can deal mobility crits upon crushing
Steps to Reproduce: Drive over a large number of partially built sandbags, eventually one will exhaust damage or detrack your tank.
Expected Outcome: Sandbags will just be run over
Actual Outcome: You may lose your tracks
---
Additional Information: Only tested with guards anvil Sherman V
![image](https://user-images.githubusercontent.com/23408530/143734811-58d77940-841b-4e22-aa08-d950e7e78528.png)

**Comment by Stoklomolvi** [comment]
Addressed by disallowing high health vehicles from getting detracked in general.
