### ISSUE TITLE
SS bunkers have low HP

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#272]
*Game Version: Spearhead II v1.1.0
Summary of Bug: ss mg bunkers are weak as hell
Steps to Reproduce: throw a nade into the bunker
Expected Outcome: does nothing, just like ost bunker
Actual Outcome:**  takes away half of health. you can one shot a bunker with a molotov.

**Comment by Stoklomolvi** [comment]
Duplicate of #271
