### ISSUE TITLE
UKF officers stand still without firing their weapons while ordering down a barrage

### ISSUE THREAD

**Issue by Luke7O7** [Stoklomolvi/Spearhead-Public#276]
**Game version-** SH II Version 1.1.0.1
**Summary of Bug-** When ordered to call down a barrage, UKF officers (T1 an T2, as T3 doesn't posses any barrages) holster their weapon while the barrage is being called down. This goes for the whole squad, not just the officer model.
**Steps to reproduce-**
-Pick UKF, doctrine Royal Tank Regiment (Picked Anvil, could extend to Hammer, and other doctrines as well)
-Call in T1 or T2 officers (T3 officers currently do not have any barrages on them which I find weird but that excludes them currently)
-Order them to call in either one of their barrages (Offensive or Support)
**Expected outcome-**Either the officer model or no one pulls down their weapons to call it down.
 **Actual outcome-** The whole squad pulls down their weapons, making it so the squad doesn't fire at all while waiting for the barrage to register.

**Additional note-** Unsure if intentional, or if it includes officers from other doctrines or factions. If intentional, will delete.

**Comment by Stoklomolvi** [comment]
Working as intended; officers cannot do anything while calling offmaps now.
