### ISSUE TITLE
[BUG] SS Prop 'Fur Das Vaterland' stacks with sprint on Strumgrenadiere and Volkssturm

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#293]
**Game Version:** Spearhead II v1.1.0.2
**Summary of Bug:** "Fur das Vaterland" Ability grants a non exclusive buff to (at least Volkssturm and Sturmgrenadieres) adding to sprint
**Steps to Reproduce:** 
    1.  Go SS Propaganda (didn't test out for other docs)
    2.  Build T3
    3.  Buy global upgrade Fur Das Vaterland

**Expected Outcome:** Ability Fur Das Vaterland (Suppression Break) replaces regular sprints for all SS units
**Actual Outcome:** On SS Prop Sturmgrenadiere and on Volkssturm, the button is added and do not replace Sprint, and the abilities are ***not*** exclusive

---
**Additional info:** This bug applies to non-doc Sturmgrenadieres after a check, and also to Jager Pionere, and SS-Panzerjäger

**Comment by Luke7O7** [comment]
The ability might include Sturm Sturmgrenadiers as well

**Comment by RobertozElGato** [comment]
Applies to all Sturmgrens and to 17th SS Grenadieres (doctrinals)
