### ISSUE TITLE
[BUG] Wehrmacht Tier 4 global upgrade for increased experience for Panzer 4 and StuG crews decreases experience gained 

### ISSUE THREAD

**Issue by Luke7O7** [Stoklomolvi/Spearhead-Public#322]
**Game Version:** Spearhead II Version 1.1.0.3
**Summary of Bug:** Tier 4 global upgrade for increased experience for Panzer 4 and StuG crews decreases experience gained 
**Steps to Reproduce:** Steps to reproduce the behavior:
-Create two Panzer 4's and two StuG III's
-Use one of each to kill a same target (In testing it was a single T34 that did not fire back)
-Purchase the upgrade at tier 4, then repeat the previous step with the other two tanks.
-Compare the experience gained

**Expected Outcome:** By the upgrades description, the tanks should be getting 25% more experience
**Actual Outcome:** The tanks that gained experience after the upgrade was purchase actually gained less experience from the same target.

---
**Additional Information:** Only tested on non doctrinal Panzer 4 H and StuG III tanks, bug probably goes across the whole roster that is affected by the upgrade.
**Attachments:** None

**Reporter:** The Kettenkrad Driver#0031

**Comment by Stoklomolvi** [comment]
Cannot reproduce; tanks appear to gain veterancy at intended rate.
