### ISSUE TITLE
[BUG] Soviet Rifle Officers mis-named

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#331]
**Game Version:** Spearhead II 1.1.0.3
**Summary Of Bug:** Russian officers not building as expected, Mayor not providing buff
**Steps To Reproduce:**
Pick Strelkovaya Diviziya (Versatile/Infantry) as the soviets
Wait until officers are available
Call in Leytenant, Kommissar or Kapitan
**Expected outcome:** builds the respective unit
**Actual outcome:** Forward building the Kommissar deploys a Leytenant, building a Leytenant deploys a Kapitan, building a Kaptian deploys a Mayor. Mayor has placeholder text and no area buff, "Leytenant" (forward deployed Kommissar) still has the Komissar's area buff

![image](https://user-images.githubusercontent.com/23408530/161451537-c8173145-d628-4994-93d0-a39fed0688cc.png)

**Reporter:** Discord user Horti-Cosmo#4378

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.3.
