### ISSUE TITLE
[BUG] USF Tank Destroyer Doctrine ability "Allied War Machine" doesn't work

### ISSUE THREAD

**Issue by Luke7O7** [Stoklomolvi/Spearhead-Public#349]
**Game Version:** Spearhead II 1.1.0.3
**Summary of Bug:** USF Tank Destroyer Doctrinal ability "Allied War Machine" doesn't work
**Steps to Reproduce:** Steps to reproduce the behavior:
-Go USF, pick TD
-Get your Command Points up to where you can use the ability
-Have some tanks of yours damaged (in testing it was two M4A2 non-doctrinal Shermans)
-Pop the ability

**Expected Outcome:** When the ability is active, all tanks under your command should repair when damaged, with your munitions income being lowered.
**Actual Outcome:** When active, the ability does not repair tanks, but I'm sure the income is lowered. Also you just wasted 120 Munitions.

---
**Additional Information:** Wish an update would land.
**Attachments:** 
![image](https://user-images.githubusercontent.com/90381045/164224827-72d9672e-e87e-4673-a4c6-923e2d03931a.png)

**Reporter:** Ya boi Kettenkrad

**Comment by Stoklomolvi** [comment]
Out-of-date; ability has been removed.
