### ISSUE TITLE
[BUG] Bloody Buckets have a weird gun among their loadout (Can't explain properly)

### ISSUE THREAD

**Issue by Luke7O7** [Stoklomolvi/Spearhead-Public#350]
**Game Version:** Spearhead II Version 1.1.0.3
**Summary of Bug:** Bloody Buckets (Cheap infantry from USF TD Company) has a rifle that looks more like an M14 Garand than a regular one.
**Steps to Reproduce:** 
-Go USF TD
-Create a Bloody Bucket squad
-Check the rifle held by each member until you get to the magazine fed Garand

**Expected Outcome:** The squad is written to be armed with M1 Garands and a Thompson squad leader
**Actual Outcome:** This out-of-place gun on one of the models (each squad has one)

---

**Additional Information:** I tested it for anomalies, though it would be like the carbine used by paras (10 round clip etc), but it acts like a garand (8 round clip), except the sound is different (That of a carbine), and the model is different.
**Attachments:** 

Look closely to the guns held by each of the two models present on the picture. 

![image](https://user-images.githubusercontent.com/90381045/164290700-8e624494-26c9-49d0-a865-734b7222a5c2.png)

UPDATE: It's a goddamn merge of two rifles, the carbine and the garand (Look at the space between the magazine and the barrel end) wtf is this rifle I have no idea. That also explains why it discharges 2 bullet casings.
![image](https://user-images.githubusercontent.com/90381045/164291266-f0833333-3dba-4006-9de8-b3750b5958a5.png)

**Reporter:** Kettenkrad

**Comment by Stoklomolvi** [comment]
Cannot reproduce.
