### ISSUE TITLE
[BUG] Satchel Charge of Bloody Buckets weirdly inconsistent (Unsure if penetration RNG or something else at play)

### ISSUE THREAD

**Issue by Luke7O7** [Stoklomolvi/Spearhead-Public#351]
**Game Version:** Spearhead II 1.1.0.3
**Summary of Bug:** Bloody Bucket Satchel Charge is weirdly inconsistent when it comes to heavier tanks
**Steps to Reproduce:** 
1) Go USF TD
2) Create one or several Bloody Bucket squads
3) Get a few heavy tanks spawned and set to be owned by enemy (Testing was done on King Tigers)
4) Throw satchel charges at the tank (The area aimed at was the rear of the tank, due to RNG the satchels would also land under the front part of the tank, as well as the sides.)

**Expected Outcome:** If a tank was caught in the explosion (Or at least in or near its epicentre), it would suffer raw damage, as it does with "Composite-B Explosive Charges"
**Actual Outcome:** Inconsistent, look below for more info.

---
**Additional Information:** I am not sure if satchel charges have a penetration score like AT guns and other stuff has, but the testing on King Tigers (And a single throw on Jagdtiger) led to them having a very large scale of result. Some satchels would only give the small crit "Crew stunned". Some would immobilize, while some would one shot a whole tank. Others would bring it to half health, some would bring it down to 10%. Where exactly the tank is related to explosion doesn't help either, as some explosions can happen right underneath and do nothing, while others explode next to the tank and kill it full

**Attachments:** None

**Reporter:** Kettenretard

**Comment by Stoklomolvi** [comment]
RNG, not a bug, though the damage/penetration of composition B could be made more consistent.
