### ISSUE TITLE
[BUG] Ammo Rack happened to a full HP Sherman

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#361]
**Game Version:** Spearhead II 1.1.1.3
**Summary of Bug:** Full HP ammoracks are still a thing, perhaps only for selected vehicles. 

**Steps to reproduce:** US Mech doctrinal Sherman 75 HVSS engaged a Panzer IV H and was ammoracked by it while having full HP and a visibility crit from AT rifle. 

**Expected outcome:** Tank loses about 50% HP, doesn't get ammoracked.

**Actual outcome:** Sherman got ammoracked.

**Additional information:** I suspect it might be an oversight with doctrinal Mech Sherman since it's the only doctrine that has it. 

**Attachments:** Replay called "Full HP Ammorack" in the 🎬replays channel, near the end of the replay, around min. 28:40

**Reporter:** Pr0fesor#0368

**Comment by Stoklomolvi** [comment]
Stemmed from an inconsistency from before the medium gun damage reduction.

Previously, 75mm guns, such as Panzer IV H main guns, would deal somewhere between 225-375 damage on a random roll. The HP cutoff for an ammo rack is 25% of total HP remaining *after the hit has dealt its damage*; on a Sherman 75mm HVSS, that threshold would be 120 HP/480 HP total without sandbags. A Panzer IV would need to roll between 360-375 on its main gun damage roll to deal enough damage to potentially proc the ammo rack critical, which, while unlikely, remained a possibility on all medium tanks.

With the medium gun damage range reduction, this scenario is no longer possible, as medium guns deal only 250-280 damage per shot, well below the threshold.
