### ISSUE TITLE
[BUG] SS Sturmgrens cannot throw smoke grenades

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#369]
**Game Version:**  Spearhead II V1.1.1.5

**Summary of Bug:** SS Sturmgrens cannot throw smoke grenades

**Expected Outcome:** throw smoke grenade

**Actual Outcome:** wherever you aim it shows warning "too close"

**Additional Information:** Picture below 

https://discord.com/channels/365319231946096644/770937541855412254/986235787001606185

https://discord.com/channels/365319231946096644/770937541855412254/986237489419280415

**Reporter:** Discord user EugenRDR#4326

**Comment by Stoklomolvi** [comment]
Old report.
