### ISSUE TITLE
[BUG] Field Maintenance upgrade for Sd.Kfz 251 permanently immobilizes it

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#377]
**Game Version:** Spearhead II 1.1.2
                 
**Summary of Bug:** "Field Maintenance" on Sd.Kfz. 251 permanently immobilizes it.
 
**Steps to Reproduce:** Buy upgrade, and toggle on "Field Maintenance." 
 
**Expected Outcome:** Halftrack should be able to move when toggled off.
 
**Actual Outcome:**  Halftrack cannot move ever again. 

**Additional Information:**  None. 

**Attachments:**

https://discord.com/channels/365319231946096644/770937541855412254/992260244153585714

**Reporter:** Discord user Constantino#9135

**Comment by Stoklomolvi** [comment]
Duplicate of #333
