### ISSUE TITLE
[BUG] Straf does not get Offensive Strike for BP1 officer.

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#394]
**Game Version:** Spearhead II 1.1.4.4
                 
**Summary of Bug:** "offensive" strike path for the straf BP 1 officer doesn't appear on the UI once upgraded
 
**Steps to Reproduce:** Pick Straf, make BP1 straf officer, choose "offensive" strike path.
 
**Expected Outcome:** fast LeIGH barrage strike appearing in officer abilities,
 
**Actual Outcome:** strike is missing, can't use the strike. 

**Additional Information:** None. 

**Attachments:**

https://discord.com/channels/365319231946096644/770937541855412254/1057745320051740763

**Reporter:** Discord user Sacrof#7898

**Comment by Stoklomolvi** [comment]
Cannot reproduce as of v1.2.2.
