### ISSUE TITLE
[BUG] UKF non-doc units do not update their names to doctrinal versions when picking a doc

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#402]
**Game Version:**  SH2 1.1.4.8 

**Summary of Bug:** At times the units do not change over when picking a doc and playing as british

**Steps to Reproduce:**  Sadly no idea 

**Expected Outcome:**  once you pick a doc the units names and icons should change

**Actual Outcome:** units and icons dont change what so ever even tho you can build the units that doc has they all go back to the default icons and unit making almost impossible to find out what you are fighting, as well you are unable to build doc specific infantry ie no eye guys for armored

**Reporter:** Discord user 𝔓𝔬𝔰𝔰𝔲𝔪 𝔭𝔦𝔢#5230

**Comment by Pariah919** [comment]
Steps to reproduce are as follows...
1. Pick a doctrine.
2. If you NEVER pick hammer or anvil, the game won't give you doctrinal names/icons.

As you can see here, I haven't picked H/A yet, so the game hasn't given me updated names.

![image](https://user-images.githubusercontent.com/46353991/217405364-ea6e3f98-ba1d-426c-b30a-329294d3c8ba.png)

After picking Hammer, it updates.

![image](https://user-images.githubusercontent.com/46353991/217405576-fe33edd4-3f76-41d0-bda4-420a3f0ce53e.png)

**Comment by RalphRoberts** [comment]
Not a bug, closing
