### ISSUE TITLE
[BUG] SS Jager cannot build 105mm howitzer

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#405]
**Game Version:** 1.1.5

**Summary of Bug:** While supposedly jager should be able to build the lefh they currently cannot

**Steps to Reproduce:** recruit pioneers and attempt to build

**Expected Outcome:** be able to build lefh howitzer

**Actual Outcome:** no icon in any category, cannot build howitzer

**Reporter:** Discord user zu#0030

**Comment by Pariah919** [comment]
Jager Sturmpiooners can build 105s, however SS Jager JagPios cannot.
![image](https://user-images.githubusercontent.com/46353991/217405005-09e6d463-98fa-4167-96d5-bc1decf77eb5.png)
![image](https://user-images.githubusercontent.com/46353991/217405113-1314eb9a-9535-42fc-931d-5f95c5b42527.png)

**Comment by RalphRoberts** [comment]
Closing, working as intended.
