### ISSUE TITLE
[BUG] Odon Jeep not affected by 'LV's can now capture' upgrade

### ISSUE THREAD

**Issue by RalphRoberts** [Stoklomolvi/Spearhead-Public#408]
**Game Version:** SH2 1.1.5 
**Summary of Bug:**  USSR odon jeep isn't affected by LV capture upgrade
**Steps to Reproduce:** go odon -> buy LV capture upgrade from t2; use jeep to cap

**Expected outcome** it captures territory
**Actual outcome** it doesn't

---

**Reporter:** Discord user Muro#4224

**Comment by Stoklomolvi** [comment]
Bug report no longer valid; ODON GAZ jeeps now capture by default as part of jeep role rework.
