### ISSUE TITLE
SS Sturmpionere loses their "destroy cover" ability when using Jäger doctrine

### ISSUE THREAD

**Issue by Stoklomolvi** [Stoklomolvi/Spearhead-Public#52]
**Game Version:** Spearhead I Public Build
**Summary of Bug:** SS Sturmpionere loses their "destroy cover" ability when using Jäger doctrine
**Steps to Reproduce:**
1) Use initial sturmpionere
2) Select Jäger doctrine
- Lose some models in initial sturmpionere squad and reinforce
- Create a new sturmpionere squad
3) Notice that the "destroy cover" ability is no longer available

**Expected Outcome:** No difference from non-doctrinal "destroy cover"
**Actual Outcome:** "Destroy cover" ability is not available

---
**Additional Information:** Does not occur if a sturmpionere squad was created before choosing Jäger doctrine and also does not lose any models; probably an entity ability and not a squad one
**Attachments:** Self-report, no attachment needed

**Comment by Pariah919** [comment]
**GAME VERSION:** 1.1.5

Testing shows this bug still exists. Sturmpioneers on SS Jager do not have destroy cover, sometimes they'll lose it on spawning in and other times it'll stay. No clue why its inconsistent like this. Might need further testing.

>Steps used to reproduce bug:


    1. Use initial sturmpionere
    2. Select Jäger doctrine
    3. Kill a model in any way.
    4. Reinforce the squad.
    5. Destroy cover is no longer avaliable.

![image](https://user-images.githubusercontent.com/46353991/217955687-aa13db50-34b7-4d88-9104-2a78764f2047.png)
![image](https://user-images.githubusercontent.com/46353991/217956149-5249fdbf-a54f-4fbb-acd3-6d274f3a54be.png)
