### ISSUE TITLE
Soviet Tank Destroyer doctrine 50kg bomb ability calls in PTAB instead

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#53]
**Game Version:** Latest Stok Patch
**Summary of Bug:** Soviet tank destroyer 50kg FAB bomb strike calls in PTAB strike instead
**Steps to Reproduce:**
1. get the 67th guards Mayor (the one locked behind final tank building for Soviet Tank Destroyer)
2. upgrade with 50kg FAB bomb strike
3. call it in

**Expected Outcome:** a 50kg bomb is dropped by IL2 on the position
**Actual Outcome:** a PTAB strike is dropped by IL2 on the position

---
**Attachments:**

here is recording of it happening ingame: https://www.dropbox.com/s/zrzzgojoif9fgz4/Company%20Of%20Heroes%202%202020-11-16%2015-39-49.mp4?dl=0

**Comment by Stoklomolvi** [comment]
I noticed this bug as well, and I am as yet unsure whether the original intention was supposed to be a PTAB drop or not. It is possible that the ability is merely misnamed, which would make it a minor bug, but if the intention was to actually drop a 50kg FAB bomb, then it is a regular bug.

**Comment by 321nick** [comment]
i think its supposed to drop a 50kg bomb, there is  already a ptab strike as a seperate upgrade, so having two wouldnt make sense.

**Comment by Stoklomolvi** [comment]
In that case, this bug will be fixed in regular bugfix order.
