### ISSUE TITLE
Commando assault barrage upgrade gives covering barrage

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#54]
**Game Version:** Latest Stok Patch
**Summary of Bug:** Commando assault barrage upgrade gives covering barrage
**Steps to Reproduce:**

1. get the british 4th commando brigade major retinue
2. upgrade with 105mm Assault Barrage
3. call it in
**Expected Outcome:** get assault barrage ability
**Actual Outcome:** ability is actually covering barrage ability

**Attachments:**
![image](https://user-images.githubusercontent.com/19196462/99356040-6d9a9a80-2877-11eb-9a0d-ece8d0aab20e.png)
![image](https://user-images.githubusercontent.com/19196462/99356053-75f2d580-2877-11eb-869e-8383d57fff05.png)

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
