### ISSUE TITLE
Soviet Artillery Penal Squad Call-in Ignores unitcap on Penals

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#56]
**Game Version:** Latest Stok Patch
**Summary of bug:** Soviet Artillery has a call in for 2x penal squads equipped with flamethrowers, but these units arent counted with the default 9 man penal squad produceable from the HQ for the unit limit
**Steps to reproduce:**

1. Call in the 2x penals with roks 3 flamethrower

**Expected outcome:** the 2x penal squads from the call in count towards the limit, and prevent any further use of said call in until both squads are dead AND producing more of said squad normally
**Actual outcome:** the 2x squads from the call in are counted as a seperate unit, and dont count towards the unit cap of the penals

**Additional Information:** tbh, i think the 16th you build normally and the 16th from the call in with flamers should both have their own seperate unit cap. i dont think its OP that way, and i think both have their own niche without the flamer call in just being flat out better in most ways. 

**Attachments:**
Heres a screenshot of post game stats from the game i played, they appear twice in the unit list. 
![image](https://user-images.githubusercontent.com/19196462/99889476-c1b0d080-2c23-11eb-87aa-79aab5bf450f.png)

and heres the replay; https://www.dropbox.com/s/5cysz4xrnx9xdql/turkey%20shoot.rec?dl=0

**Comment by Stoklomolvi** [comment]
Ability was removed from the game; this bug is no longer valid.
