### ISSUE TITLE
Royal Tank 5.5inch AT arty removes primary ability

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#59]
**Game Version:** stok latest version
**Summary of Bug:** Royal tank 7th armoured division major retinue, upgrading too 5.5 inch AT arty blocks out the primary ability aswell 
**Steps to reproduce:**

1. go royal tank
2. get the major retinue
3.upgrade the 5.5 inch AT arty

**Expected outcome:** replaces the secondary ability
**Actual outcome:** replaces the secondary ability and removes the primary one

**Attachments:**
![image](https://user-images.githubusercontent.com/19196462/100599039-81a9b780-32cd-11eb-9546-0ad7386220ed.png)
![image](https://user-images.githubusercontent.com/19196462/100599053-87070200-32cd-11eb-8a0d-0f35a698d409.png)

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
