### ISSUE TITLE
2 STG's instead of 3

### ISSUE THREAD

**Issue by Stoklomolvi** [Stoklomolvi/Spearhead-Public#6]
**Game Version:** Current Official Patch
**Summary of Bug:** 2 STG's instead of 3
**Steps to Reproduce:**
1) Go Wehrmacht Ost Division
2) Make 25th Panzergrenadier division Panzergrenadiere unit from T1
3) Equip them with 2x STG upgrade and a Panzerschreck

**Expected Outcome:** The Unit is noted to have an STG on arrival, meaning after the upgrade it should have 3 
**Actual Outcome:** There are only 2 STG's on the unit models

---
**Additional Information:** Hunter pointed out that it could be the Panzerschreck that took one of the STG's away
**Attachments:** ![image](https://cdn.discordapp.com/attachments/489426395097858063/769840650815799316/unknown.png)

**Reporter:** Discord user Luke7O7#8538

**Comment by Luke7O7** [comment]
Heh, the first reported bug of mine
 Back when the new update was fresh and nice

**Comment by Pariah919** [comment]
**GAME VERSION:** 1.1.5

Testing shows that Ost Pgrens have the correct amount of STGs.

![image](https://user-images.githubusercontent.com/46353991/217953653-f20955dd-aeff-4526-b322-52239d993257.png)

**Comment by Pariah919** [comment]
Closing as **resolved**. As it would appear that the unit gets the proper amount of STGs now.
