### ISSUE TITLE
Propaganda "for the fatherland" doesnt actually prevent retreat

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#60]
**Game Version:** spearhead stok 
**Summary of Bug:** propaganda doctrine ability "for the fatherland" doesnt actually prevent retreat
**Steps to reproduce:**

1. go ss propaganda
2. use ability

**Expected outcome:** retreat ability unusable during ability
**Actual outcome:** retreat ability still usable during ability

**Attachments:**
![RelicCoH2_2020-12-02_06-35-21](https://user-images.githubusercontent.com/19196462/100871764-c6b91f80-346e-11eb-9e89-fdd413fc2bfd.jpg)

**Comment by Stoklomolvi** [comment]
Fixed by the officer rework.
