### ISSUE TITLE
Shared cooldown for Battlegroups and Off-Map CB

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#64]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Shared cooldown of Off map Counter Barrage and Battlegroup call instant for Ost-division
**Steps to Reproduce:**
-Go Wehr Ost Doctrine
-Make a Forward HQ and call in one of the battlegroups

**Expected Outcome:** The units arrive normally and the long cooldown of Battlegroup call instant is initiated
**Actual Outcome:** Ost's Doctrinal CB Ability is also included in the cooldown

------------------------------------------------
**Additional Information:** None
**Attachments:** None

**Reporter:** Luke7O7#8538

![image](https://user-images.githubusercontent.com/76040686/102201850-ec124880-3ec6-11eb-9bd7-db1456e71b70.png)

**Comment by Stoklomolvi** [comment]
No longer valid as the ability counter-battery was removed.
