### ISSUE TITLE
222 Scout car upgrades changing

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#68]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** 222 upgrade phasing out
**Steps to Reproduce:**
1) Go Wehrmacht
2) Make a 221/222
3) Upgrade it with a 2 cm cannon
4) Wait for the upgrade to finish and then upgrade the passive repair

**Expected Outcome:** You can buy passive repair
**Actual Outcome:** It's removed in favour of "Signal Howitzer Barrage"

---

**Additional Information:** If clicked as the 2 cm is upgrading it's possible to upgrade the passive heal and 2 cm cannon
**Attachments:** Fresh 222

**Reporter:** Luke7O7#8538

2 cm cannon and Passive repair both available :
![image](https://user-images.githubusercontent.com/76040686/102204946-ca1ac500-3eca-11eb-900e-1491a7c71bd7.png)

![image](https://user-images.githubusercontent.com/76040686/102204999-e0c11c00-3eca-11eb-841f-1cba2b9f8cd2.png)

222 with upgraded 2 cm cannon now has the Passive Repair upgrade replaced :

![image](https://user-images.githubusercontent.com/76040686/102250590-01599800-3f04-11eb-8b38-31b364670939.png)

**Comment by Stoklomolvi** [comment]
@RobertozElGato pictures don't seem to look quite right.

**Comment by Stoklomolvi** [comment]
This bug was resolved when coordinated barrage abilities were removed from the game.
