### ISSUE TITLE
Camo netting upgrade for Command Luchs

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#70]
**Game Version:** Latest Public Stok Patch
**Summary of Bug:** Camo Netting denied for Command Luchs
**Steps to Reproduce:**
1) Go Wehr Panzer
2) Spawn the T1 Officer in the tank
3) Upgrade with auto repair, wait until finished
3) Try to upgrade Camouflage Netting

**Expected Outcome:** The option is available
**Actual Outcome:** It's blocked due to "Other upgrades"
 
---

**Additional Information:** If this is an intentional decision then it's a dumb decision
**Attachments:**

**Reporter:** Luke7O7#8538

![image](https://user-images.githubusercontent.com/76040686/102206052-524d9a00-3ecc-11eb-85b5-1dcac4079a3b.png)

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
