### ISSUE TITLE
Soviet officer multiple illumination barrage

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#75]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Officer Ilumination Barrage multiple uses
**Steps to Reproduce:** 
1) Go Soviet Artillery
2) Spawn the first officer
3) Call in an Illumination barrage

**Expected Outcome:** The barrage goes on cooldown after the activation
**Actual Outcome:** The coldown appears but the icon is still visible and the Illumination Barrage can be used multiple times

---

**Additional Information:** Similar to my already reported SS Officer Mark Target ability (#23)
**Attachments:** 

(Screenshot provided by monstergeek#7218, under 1.0.5, the 15/12/2020)

**Reporter:** Luke7O7#8538

![image](https://user-images.githubusercontent.com/76040686/102277854-26accd00-3f29-11eb-93cd-557ea188e9a5.png)

**Comment by Stoklomolvi** [comment]
This bug might be fixed as of v1.0.5, as it was reported before my "shared cooldown" random/scattershot fix.
