### ISSUE TITLE
Panzerfaust not replacing satchell

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#81]
**Game Version:** Spearhead 1.0.4
**Summary of Bug:** Panzerfaust and Satchell both available
**Steps to Reproduce:** 
1) Go SS-Sturm division
2) Train a 2. SS-Panzer-Division Panzergrenadiere (Infantry HQ)
3) Upgrade with global Panzerfaust upgrade or only on the squad

**Expected Outcome:** The faust replaces the satchell
**Actual Outcome:** Both abilities are available to the squad

---

**Additional Information:** Both abilites available implies insane AT capacities for the squad (cooldowns are independent) and bug #80
**Attachments:** 

**Reporter:** Robertoz#0911

![image](https://user-images.githubusercontent.com/76040686/102249101-44b30700-3f02-11eb-883f-0bab6949f18c.png)

**Comment by Stoklomolvi** [comment]
Closely related to #80; if this bug is fixed, I suspect #80 to be fixed as well.
