### ISSUE TITLE
Missing sandbag armor for USF Armor "Easy Eights"

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#86]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** US Armor Doc Easy Eight missing sandbag armor upgrade
**Steps to Reproduce:** 
1) Go USF Armor
2) Deploy a M4A3E8

**Expected Outcome:** A sandbag armor upgrade should be available without prerequisite, or with veterancy/doctrine prerequisite
**Actual Outcome:** No sandbag armor upgrade available

---

**Additional Information:** None
**Attachments:** None

**Reporter:** Constantino#9135

**Comment by RalphRoberts** [comment]
This isn't a bug, it's a feature request.
