### ISSUE TITLE
SS Mech "For the Fatherland" not buffing nor preventing retreat

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#90]
**Game Version:** Spearhead 1.0.5
**Summary of Bug:** SS Mech "For the Fatherland" not affecting units and not preventing retreat
**Steps to Reproduce:**
1) Go SS Mech
2) Call in a battlegroup of the "snow infantry"
3) Click the ability "For the Fatherland" that "prevents retreat and effects infantry in friendly sector"

**Expected Outcome:** prevents retreat and effects infantry in friendly sector
**Actual Outcome:** Snow infantry isn't buffed at all, while other infantry that *is* affected can retreat freely while the ability is active

---

**Additional Information:** None
**Attachments:** None

**Reporter:** Luke7O7#8538

**Comment by Stoklomolvi** [comment]
Ability was reworked by officers; bug is no longer valid.
