### ISSUE TITLE
USF Armor officer buff (no text)

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#93]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** No text for Lieutenant and Captain (And probably Major) 
**Steps to Reproduce:** 
1) Go USF Tank
2) Spawn both officers in the tank
3) Put some infantry near them

**Expected Outcome:** There are aura effects around the officers that boost infantry and / or vehicles
**Actual Outcome:** No boosts on vehicles, infantry has the little officer icon but no text

---
**Additional Information:** None
**Attachments:**

**Reporter:** Luke7O7#8538

![image](https://user-images.githubusercontent.com/76040686/102601540-976a0a00-4120-11eb-8f39-9b2bdf31fc54.png)

**Comment by Stoklomolvi** [comment]
Officers no longer provide auras; bug is no longer valid.
