### ISSUE TITLE
UK armour valentine counts as both major and captain, has wrong crew

### ISSUE THREAD

**Issue by 321nick** [Stoklomolvi/Spearhead-Public#97]
**Game Version:** 1.0.5 stok version
**Summary of Bug:** the UK armour valentine counts as both captain and major when o nthe field, and prevents call in of the captain when on the field, and the crew of the UK valentine is actually the major when it should be the captain
**Steps to reproduce:**

1. go UK armour
2. get valentine command tank
3. try to get command cromwell or captain or any other officer, besides the liutenant (he works fine)

**Expected outcome:** valentine counts as captain, not as major
**Actual outcome:** valentine counts as both, and prevents call in from 2 officers

**Additional Information/attachments:**
here i have the valentine on the field, and i cant get the Captain:
![image](https://user-images.githubusercontent.com/19196462/102685695-7650fa00-41b0-11eb-8c4b-0f577a2b4903.png)

or the major: 
![image](https://user-images.githubusercontent.com/19196462/102685700-7cdf7180-41b0-11eb-8b94-3bb720bbdeaf.png)

when the valentine is killed and only the crew remain, i can get the captain, (which is weird since the valentines crew is supposed too be the captain from the tooltip on one of the previous screenshots, but is instead the major):
![image](https://user-images.githubusercontent.com/19196462/102685704-8668d980-41b0-11eb-84bc-761b7cc021a6.png)

but not the major, since the crew of the valentine is mistakenly the major, not the captain:
![image](https://user-images.githubusercontent.com/19196462/102685740-c039e000-41b0-11eb-917d-9b916c20f44c.png)

**Comment by Whitenor** [comment]
I tested it just now, the bug appears only when the anvil specialization is chosen. In Hammer, there is no problem with the commanders.

**Comment by Stoklomolvi** [comment]
Fixed in v1.1.0.
