### ISSUE TITLE
Sturm doctrine T3 Officer Barrages

### ISSUE THREAD

**Issue by RobertozElGato** [Stoklomolvi/Spearhead-Public#99]
**Game Version:** Spearhead version 1.0.5
**Summary of Bug:** Sturm T3 officer (in his tank) having strikes that disappears
**Steps to Reproduce:** 
1) Go SS Sturm-tactics
2) Spawn T3 officer in last half-track HQ
3) Buy the Flame Barrage/Nebelwerfer Barrage upgrade

**Expected Outcome:** It replaces primary barrage (10.5cm HE barrage)
**Actual Outcome:** Replaces primary barrage and makes secondary disappear (15cm HE Barrage)

---
**Additional Information:** Note that the officer on foot have 15cm HE Barrage as primary and Sector artillery as secondary
**Attachments:** None

**Comment by Stoklomolvi** [comment]
Invalidated by v1.1.0.
